name: braven_data
description: "Scientific data input, aggregation, and processing library for braven_charts."
version: 0.1.0
publish_to: "none" # Prevent accidental publishing

environment:
  sdk: ">=3.0.0 <5.0.0"

dependencies:
  dart_fit_decoder:
    git:
      url: https://github.com/forcegage-pvm/dart_fit_decoder
      ref: main

dev_dependencies:
  # Testing framework for unit tests and benchmarks
  test: ^1.26.3
  # Linting
  lints: ^6.1.0
  # Path utilities for testing
  path: ^1.9.0
